/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import edu.info0502.poker.*;

import java.util.ArrayList;
import java.util.List;

import javax.print.attribute.standard.Media;

public class App {
    public static void main(String[] args) {
        // TP2
        Carte c1 = new Carte(Couleur.Pique, Vrai_Couleur.Rouge, 12);
        // System.out.println(c1.toString());
        Paquet paquet = new Paquet();
        System.out.println(paquet.toString());

        Talon talon = new Talon(3);
        talon.melanger();
        System.out.println(talon.toString());

        Main main1 = new Main(talon, 5);
        System.out.println(main1.toString());
        Main main2 = new Main(talon, 5);
        System.out.println(main2.toString());

        if (main1.estPlusForte(main2)) {
            System.out.println("Main 1 plus forte\n");
        } else {
            System.out.println("Main 2 plus forte\n");
        }

        Main main3 = new Main();
        Main main4 = new Main();

        for (int i = 0; i < 5; i++) {
            main1.distribuerCarte(i, talon);
            main2.distribuerCarte(i, talon);
            main3.distribuerCarte(i, talon);
            main4.distribuerCarte(i, talon);
        }
        System.out.println(main1.toString());
        System.out.println(main2.toString());
        System.out.println(main3.toString());
        System.out.println(main4.toString());

        if (main1.estPlusForte(main2) && main1.estPlusForte(main3) && main1.estPlusForte(main4)) {
            System.out.println("Victoire joueur 1\n");
        } else if (main2.estPlusForte(main1) && main2.estPlusForte(main3) && main2.estPlusForte(main4)) {
            System.out.println("Victoire joueur 2\n");
        } else if (main3.estPlusForte(main1) && main3.estPlusForte(main2) && main3.estPlusForte(main4)) {
            System.out.println("Victoire joueur 3\n");
        } else
            System.out.println("Victoire joueur 4\n");

        // ##############################################################
        // texas hold'em

        Main[] Joueurs = new Main[4];
        for (int i = 0; i < 4; i++) {
            Joueurs[i] = new Main(talon, 2);
        }
        for (int i = 0; i < 2; i++) {
            Joueurs[0].distribuerCarte(i, talon);
            Joueurs[1].distribuerCarte(i, talon);
            Joueurs[2].distribuerCarte(i, talon);
            Joueurs[3].distribuerCarte(i, talon);
        }
        Main Croupier = new Main(talon, 5);
        Carte[] cartesCroupier = Croupier.getMain();
        List<Carte[]> CombiFortes = new ArrayList<>();

        // Pour chaque joueur
        for (int i = 0; i < 4; i++) {
            List<Carte[]> combinaisons = Joueurs[i].getAllCombinations(cartesCroupier);
            Carte[] meilleureCombinaison = combinaisons.get(0); // On part du principe que la première est la plus forte

            // Comparer chaque combinaison pour trouver la plus forte
            for (int j = 1; j < combinaisons.size(); j++) {
                Carte[] combinaisonActuelle = combinaisons.get(j);

                // Créer des objets `Main` temporaires pour utiliser `estPlusForte`
                Main mainTemp1 = new Main(meilleureCombinaison);
                Main mainTemp2 = new Main(combinaisonActuelle);

                // Si la combinaison actuelle est plus forte, on met à jour la meilleure
                // combinaison
                if (mainTemp2.estPlusForte(mainTemp1)) {
                    meilleureCombinaison = combinaisonActuelle;
                }
            }

            // Ajouter la combinaison la plus forte de ce joueur dans la liste CombiFortes
            CombiFortes.add(meilleureCombinaison);
        }

        // Affichage des meilleures combinaisons pour chaque joueur
        for (int i = 0; i < CombiFortes.size(); i++) {
            Main combinaison = new Main(CombiFortes.get(i));
            System.out.println("Combinaison forte du joueur " + (i + 1) + " : ");
            System.out.println(combinaison.toString());
            System.out.println();
        }

        int JV = 0;

        for (int i = 1; i < CombiFortes.size(); i++) {
            Main maintemp1 = new Main(CombiFortes.get(i));
            Main maintemp2 = new Main(CombiFortes.get(JV));
            
            if (maintemp1.estPlusForte(maintemp2)) {
                JV = i;
            }
        }
        
        Main JoueurGagnant = new Main(CombiFortes.get(JV));
        System.out.println("Victoire joueur : " + (JV + 1) + " avec : \n" + JoueurGagnant.toString());
        

    }
}
